services:
  admin.mail:
    class: WebEtDesign\MailerBundle\Admin\MailAdmin
    arguments:
      - ~
      - WebEtDesign\MailerBundle\Entity\Mail
      - WebEtDesign\MailerBundle\Controller\MailAdminController
      - '@parameter_bag'
      - '@WebEtDesign\MailerBundle\Services\MailEventManager'
    tags:
      - { name: sonata.admin, manager_type: orm, group: CMS, label: Mails }
    public: true
    calls:
      - [ setTemplate, [ 'button_test', '@@WDMailer/admin/mail/test_button.html.twig' ] ]
